### ISSUE TITLE
Are you sure you want to delete [Admin Func]

### ISSUE THREAD

**Issue by zollf** [zollf/CITS3200#69]
Have a pop up to confirm deletion of item

**Comment by APM246** [comment]
Since we're not using a CSS framework like Bootstrap I'm just going to use some CSS I've found online for the pop-up.

**Comment by zollf** [comment]
this could be a potential idea 
- https://www.w3schools.com/js/tryit.asp?filename=tryjs_confirm
- https://www.w3schools.com/js/js_popup.asp

feel free to use anything

**Comment by APM246** [comment]
oh yea the confirm() or alert() function would be a super easy solution lol

**Comment by APM246** [comment]
but I think to be consistent with the theme of the website I need to make a custom popup modal as the system popup (created by confirm() or alert()) cannot be customised.

**Comment by zollf** [comment]
It seems easy to slot in here https://github.com/zollf/CITS3200/blob/main/app/resources/static/scripts/delete.js as it is already a js script.

I don't know the complete compatibility either.
 
I trust your decision either way.
