### ISSUE TITLE
Password Reset [Admin Func]

### ISSUE THREAD

**Issue by zollf** [zollf/CITS3200#73]
Ideally, we want to do this without email. So maybe just assign a temp password

**Comment by APM246** [comment]
If the system assigns them a temp password, this means they wouldn't be able to change it unless they were an admin.

**Comment by zollf** [comment]
Yea, you probably need to create a reset password page then

**Comment by APM246** [comment]
But that isn't safe because anyone can change someone else's password by clicking forgot password and providing someone else's username. 

Sending a one-time password reset link via email would be safe.

**Comment by zollf** [comment]
So basically what I mean, is that you have an admin panel button that resets a password, and gives them a reset password link. That link should have a generated token in the URL so that only those with the URL can access it. Then uni park would just have to send it to them. Once they have reset password the token is rendered invalid. You can give them a temp code that they have to input as well if you want more security. I want to avoid doing password reset by emails. Ideally the only difference between this and other reset passwords, is the person that lost their password can't do it themselves, and uni park has to give the URL.

**Comment by APM246** [comment]
I think it would be a good idea to send an email to James to confirm he is ok with this design. I wouldn't want to spend a decent amount of time on this only for him to say in the retrospective that he would have preferred a different flow.

**Comment by zollf** [comment]
Ok. Either way you'll still have to do url with a token in query param which takes them to reset password page, and if their token is invalid it wont let them reset.
